# Base configs
#baseurl: "https://patrikstoian.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Patrik Stoian Fotograf | Fotograf de nuntă din Timișoara | Fotograf de botez din Timișoara"
subtitle: ""
author: "Patrik Stoian"
header:
 title: "Patrik Stoian"
 subtitle: " - Fotograf"
footer:
 name: "Fotograf din Timisoara"
 bio: ""
web_design: "PS"
social_urls:
  instagram: "https://www.instagram.com/patrik_stoian_fotograf"
  facebook: "https://www.facebook.com/patrik.stoian"
