# Base configs
#baseurl: "https://patrikstoian.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Patrik Stoian Fotograf"
subtitle: ""
author: "Patrik Stoian"
header:
 title: "Patrik Stoian"
 subtitle: " - Fotograf"
footer:
 name: "Fotograf din Timisoara"
 bio: "Bună, sunt Patrik și doresc să îți prezint serviciile foto pe care le ofer. Am pornit în călătoria mea de fotograf cu poze realizate la evenimente business, petreceri de firmă, nunți, botezuri, dar și ședințe foto de faimilie sau portofoliu. Pozele mele oglindesc pasiunea și profesionalismul oferit la fiecare ședință foto. Ofer ședințe foto la cea mai înaltă calitate în zona județului Timiș și nu numai."
web_design: "PS"
social_urls:
  instagram: "https://www.instagram.com/patrikstoian_"
  facebook: "https://www.facebook.com/patrik.stoian"
